apiVersion: apps/v1
kind: Deployment
metadata:
  name: pop-stats-hyb
  labels:
    env: staging
spec:
  replicas: 3
  template:
    spec:
      containers:
          - name: pop-stats-hyb
            livenessProbe:
              httpGet:
                path: /h
                port: 8080
              initialDelaySeconds: 30
              periodSeconds: 15
            env:
              - name: SITE_NAME
                value: "Population Stats Staging"
