# replace "raniamoh-demo-playg-sharedvpc" in the three targets below with your actual project(s)
apiVersion: deploy.cloud.google.com/v1
kind: DeliveryPipeline
metadata:
  name: hybrib-pipeline
serialPipeline:
  stages:
    - targetId: dev-anthos
      profiles:
        - dev
    - targetId: staging-anthos
      profiles:
        - stagging
    - targetId: prod-anthos
      profiles:
        - prod
---

apiVersion: deploy.cloud.google.com/v1
kind: Target
metadata:
  name: dev-anthos
description: dev cluster
anthosCluster:
  membership: projects/raniamoh-playground/locations/global/memberships/devops-demo-admin
executionConfigs:
  - privatePool:
      workerPool: projects/raniamoh-playground/locations/us-central1/workerPools/anthos
      serviceAccount: 189908348872@cloudbuild.gserviceaccount.com
    usages:
      - RENDER
      - DEPLOY
---

apiVersion: deploy.cloud.google.com/v1
kind: Target
metadata:
  name: staging-anthos
description: staging cluster
anthosCluster:
  membership: projects/raniamoh-playground/locations/global/memberships/cloud-demo-fleet-membership
---

apiVersion: deploy.cloud.google.com/v1
kind: Target
metadata:
  name: prod-anthos
description: prod cluster
requireApproval: true
anthosCluster:
  membership: projects/raniamoh-playground/locations/global/memberships/regional-clusterwi-region
