apiVersion: skaffold/v2beta16
kind: Config
metadata:
  name: hybrib-pipeline
build:
# Uncomment if you're using minikube for local dev and don't want to push to Artifact Registry
#  local: 
#    push: false
  artifacts:
  - image: pop-stats-hyb
    context: samples/pop-kustomize/app
    docker:
      dockerfile: Dockerfile
deploy:
  kustomize:
    paths: 
      - k8s-hybrid/overlays/dev
portForward:
- resourceType: deployment
  resourceName: pop-stats-hyb
  port: 8080 
  localPort: 8080
profiles:
  - name: staging
    deploy:
      kustomize:
        paths: 
          -k8s-hybrid/overlays/staging
  - name: prod
    deploy:
      kustomize:
        paths: 
          - k8s-hybrid/overlays/prod