apiVersion: apps/v1
kind: Deployment
metadata:
  name: pop-stats-hyb
  labels:
    env: test
spec:
  template:
    spec:
      containers:
      - name: pop-stats-hyb
        env:
          - name: SITE_NAME
            value: "Population Stats Test"
