gcloud beta container --project "raniamoh-playground" clusters create "application-cluster" \
--gateway-api=standard \
--zone "europe-west1-b" --no-enable-basic-auth --cluster-version "1.30.3-gke.1639000" \
--release-channel "regular" --machine-type "e2-standard-4" --image-type "COS_CONTAINERD" \
--disk-type "pd-balanced" --disk-size "100" --metadata disable-legacy-endpoints=true \
--scopes "https://www.googleapis.com/auth/devstorage.read_only","https://www.googleapis.com/auth/logging.write","https://www.googleapis.com/auth/monitoring","https://www.googleapis.com/auth/servicecontrol","https://www.googleapis.com/auth/service.management.readonly","https://www.googleapis.com/auth/trace.append" \
--num-nodes "1" --logging=SYSTEM,WORKLOAD,API_SERVER,SCHEDULER,CONTROLLER_MANAGER \
--monitoring=SYSTEM,API_SERVER,SCHEDULER,CONTROLLER_MANAGER,STORAGE,POD,DEPLOYMENT,STATEFULSET,DAEMONSET,HPA,CADVISOR,KUBELET \
--enable-ip-alias --network "projects/raniamoh-playground/global/networks/default" \
--subnetwork "projects/raniamoh-playground/regions/europe-west1/subnetworks/default"\
 --no-enable-intra-node-visibility --default-max-pods-per-node "110" \
 --security-posture=standard --workload-vulnerability-scanning=enterprise \
 --no-enable-master-authorized-networks \
 --addons HorizontalPodAutoscaling,HttpLoadBalancing,GcePersistentDiskCsiDriver \
 --enable-autoupgrade --enable-autorepair --max-surge-upgrade 1 --max-unavailable-upgrade 0 \
 --binauthz-evaluation-mode=DISABLED --enable-managed-prometheus \
 --workload-pool "raniamoh-playground.svc.id.goog" \
 --enable-shielded-nodes --fleet-project=raniamoh-playground --node-locations "europe-west1-b"