---
apiVersion: v1
kind: Pod
metadata:
  namespace: xxxxx
  name: jwt
  labels:
    app: jwt
spec:
  containers:
  - image:xxxxxxxxx/jwt:v1
    name: server
    ports:
    - containerPort: 8080
    env:
    - name: PORT
      value: "8080"
    # This environment variable enables debugging support for the container.
    # Remove this to disable the debug build.
    - name: JAVA_TOOL_OPTIONS
      value: -agentlib:jdwp=transport=dt_socket,server=y,address=5005,suspend=n,quiet=y
  serviceAccountName: app1-ksa
     
