---
apiVersion: v1
kind: Pod
metadata:
  namespace: dotnetcore
  name: java-hello-world
  labels:
    app: java-hello-world
spec:
  containers:
  - image: us-central1-docker.pkg.dev/raniamoh-playground/raniamoh/java-hello-world:v1
    name: server
    ports:
    - containerPort: 8080
    env:
    - name: PORT
      value: "8080"
    # This environment variable enables debugging support for the container.
    # Remove this to disable the debug build.
    - name: JAVA_TOOL_OPTIONS
      value: -agentlib:jdwp=transport=dt_socket,server=y,address=5005,suspend=n,quiet=y
  serviceAccountName: app1-ksa
     