apiVersion: v1
kind: Service
metadata:
  namespace: dotnetcore
  name: java-hello-world-external
spec:
  type: LoadBalancer
  selector:
    app: java-hello-world
  ports:
  - name: http
    port: 80
    targetPort: 8080