steps:
# Install dependencies
- name: python
  entrypoint: pip
  args: ["install", "-r", "requirements.txt", "--user"]

# Docker Build
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t',
         'europe-west4-docker.pkg.dev/PROJECT_ID/ARTIFACT_REPOSITRY_NAME/error-app:latest', '.']

# Docker push to Google Artifact Registry
- name: 'gcr.io/cloud-builders/docker'
  args: ['push',  'europe-west4-docker.pkg.dev/PROJECT_ID/ARTIFACT_REPOSITRY_NAME/error-app:latest']

# Store images in Google Artifact Registry
images:
- europe-west4-docker.pkg.dev/PROJECT_ID/ARTIFACT_REPOSITRY_NAME/error-app:latest